// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: YouRetires

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
void ui_event_MainScreen(lv_event_t * e);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_MainPanel;
lv_obj_t * ui_DaysPanel;
lv_obj_t * ui_lblDaysUntil;
lv_obj_t * ui_Days;
lv_obj_t * ui_lblDays;
lv_obj_t * ui_YMDPanel;
lv_obj_t * ui_Years1;
lv_obj_t * ui_lblYears1;
lv_obj_t * ui_Months1;
lv_obj_t * ui_lblMonths1;
lv_obj_t * ui_Days1;
lv_obj_t * ui_lblDays1;
lv_obj_t * ui_CurrentTime;
lv_obj_t * ui_CurrentTimeHeader;
lv_obj_t * ui_RetireDate;
lv_obj_t * ui_RetireDateHeader;
lv_obj_t * ui_Status1;
// CUSTOM VARIABLES


// SCREEN: ui_RetirementAdjustScreen
void ui_RetirementAdjustScreen_screen_init(void);
void ui_event_RetirementAdjustScreen(lv_event_t * e);
lv_obj_t * ui_RetirementAdjustScreen;
lv_obj_t * ui_RetirementAdjustPanel;
lv_obj_t * ui_lblRetirementAdjust;
void ui_event_RetirementCalendar(lv_event_t * e);
lv_obj_t * ui_RetirementCalendar;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_MainScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_RetirementAdjustScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0,
                          &ui_RetirementAdjustScreen_screen_init);
        _ui_screen_delete(&ui_MainScreen);
    }
}

void ui_event_RetirementAdjustScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_MainScreen_screen_init);
        _ui_screen_delete(&ui_RetirementAdjustScreen);
    }
}

void ui_event_RetirementCalendar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        GetDateFromCalendarWidget(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_MainScreen_screen_init();
    ui_RetirementAdjustScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_MainScreen);
}
