// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: YouRetires

#include "ui.h"

void GetDateFromCalendarWidget(lv_event_t * e)
{
	// Your code here
}

void GetDateFromCalendarWidget2(lv_event_t * e)
{
	// Your code here
}
