// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: YouRetires

#include "ui.h"

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_MainScreen, &ui_img_bluehexbg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainPanel = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_MainPanel, 738);
    lv_obj_set_height(ui_MainPanel, 427);
    lv_obj_set_x(ui_MainPanel, 0);
    lv_obj_set_y(ui_MainPanel, 15);
    lv_obj_set_align(ui_MainPanel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_MainPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_MainPanel, &ui_img_bluehexbg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DaysPanel = lv_obj_create(ui_MainPanel);
    lv_obj_set_width(ui_DaysPanel, 687);
    lv_obj_set_height(ui_DaysPanel, 190);
    lv_obj_set_align(ui_DaysPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DaysPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DaysPanel, lv_color_hex(0x1F3FC2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DaysPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblDaysUntil = lv_label_create(ui_DaysPanel);
    lv_obj_set_width(ui_lblDaysUntil, 678);
    lv_obj_set_height(ui_lblDaysUntil, 52);
    lv_obj_set_align(ui_lblDaysUntil, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblDaysUntil, "WORK DAYS UNTIL RETIREMENT");
    lv_obj_set_style_text_color(ui_lblDaysUntil, lv_color_hex(0xBDBEBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblDaysUntil, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblDaysUntil, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblDaysUntil, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Days = lv_label_create(ui_DaysPanel);
    lv_obj_set_width(ui_Days, 189);
    lv_obj_set_height(ui_Days, 80);
    lv_obj_set_align(ui_Days, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Days, "9,999");
    lv_obj_set_style_text_color(ui_Days, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Days, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Days, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Days, &ui_font_MontserratMedium60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Days, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Days, lv_color_hex(0xE26F00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Days, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Days, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Days, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Days, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblDays = lv_label_create(ui_DaysPanel);
    lv_obj_set_width(ui_lblDays, 83);
    lv_obj_set_height(ui_lblDays, 39);
    lv_obj_set_x(ui_lblDays, 143);
    lv_obj_set_y(ui_lblDays, -20);
    lv_obj_set_align(ui_lblDays, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lblDays, "days");
    lv_obj_set_style_text_color(ui_lblDays, lv_color_hex(0xBDBEBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblDays, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblDays, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblDays, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_YMDPanel = lv_obj_create(ui_MainPanel);
    lv_obj_set_width(ui_YMDPanel, 687);
    lv_obj_set_height(ui_YMDPanel, 96);
    lv_obj_set_x(ui_YMDPanel, 0);
    lv_obj_set_y(ui_YMDPanel, 10);
    lv_obj_set_align(ui_YMDPanel, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_YMDPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_YMDPanel, lv_color_hex(0x1F3FC2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_YMDPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Years1 = lv_label_create(ui_YMDPanel);
    lv_obj_set_width(ui_Years1, 93);
    lv_obj_set_height(ui_Years1, 76);
    lv_obj_set_x(ui_Years1, -270);
    lv_obj_set_y(ui_Years1, 0);
    lv_obj_set_align(ui_Years1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Years1, "99");
    lv_obj_set_style_text_color(ui_Years1, lv_color_hex(0xBDBEBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Years1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Years1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Years1, &ui_font_MontserratMedium60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Years1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Years1, lv_color_hex(0x540592), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Years1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Years1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Years1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Years1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblYears1 = lv_label_create(ui_YMDPanel);
    lv_obj_set_width(ui_lblYears1, 98);
    lv_obj_set_height(ui_lblYears1, 39);
    lv_obj_set_x(ui_lblYears1, -171);
    lv_obj_set_y(ui_lblYears1, 2);
    lv_obj_set_align(ui_lblYears1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblYears1, "years");
    lv_obj_set_style_text_color(ui_lblYears1, lv_color_hex(0xBDBEBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblYears1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblYears1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblYears1, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Months1 = lv_label_create(ui_YMDPanel);
    lv_obj_set_width(ui_Months1, 93);
    lv_obj_set_height(ui_Months1, 76);
    lv_obj_set_x(ui_Months1, -59);
    lv_obj_set_y(ui_Months1, 0);
    lv_obj_set_align(ui_Months1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Months1, "99");
    lv_obj_set_style_text_color(ui_Months1, lv_color_hex(0xBDBEBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Months1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Months1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Months1, &ui_font_MontserratMedium60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Months1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Months1, lv_color_hex(0x540592), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Months1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Months1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Months1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Months1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblMonths1 = lv_label_create(ui_YMDPanel);
    lv_obj_set_width(ui_lblMonths1, 142);
    lv_obj_set_height(ui_lblMonths1, 39);
    lv_obj_set_x(ui_lblMonths1, 60);
    lv_obj_set_y(ui_lblMonths1, 2);
    lv_obj_set_align(ui_lblMonths1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMonths1, "months");
    lv_obj_set_style_text_color(ui_lblMonths1, lv_color_hex(0xBDBEBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblMonths1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblMonths1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblMonths1, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Days1 = lv_label_create(ui_YMDPanel);
    lv_obj_set_width(ui_Days1, 93);
    lv_obj_set_height(ui_Days1, 76);
    lv_obj_set_x(ui_Days1, 190);
    lv_obj_set_y(ui_Days1, 0);
    lv_obj_set_align(ui_Days1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Days1, "99");
    lv_obj_set_style_text_color(ui_Days1, lv_color_hex(0xBDBEBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Days1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Days1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Days1, &ui_font_MontserratMedium60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Days1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Days1, lv_color_hex(0x540592), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Days1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Days1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Days1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Days1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblDays1 = lv_label_create(ui_YMDPanel);
    lv_obj_set_width(ui_lblDays1, 83);
    lv_obj_set_height(ui_lblDays1, 39);
    lv_obj_set_x(ui_lblDays1, 281);
    lv_obj_set_y(ui_lblDays1, 2);
    lv_obj_set_align(ui_lblDays1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblDays1, "days");
    lv_obj_set_style_text_color(ui_lblDays1, lv_color_hex(0xBDBEBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblDays1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblDays1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblDays1, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CurrentTime = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_CurrentTime, 286);
    lv_obj_set_height(ui_CurrentTime, 77);
    lv_obj_set_x(ui_CurrentTime, -200);
    lv_obj_set_y(ui_CurrentTime, -163);
    lv_obj_set_align(ui_CurrentTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurrentTime, "23:48  12/25");
    lv_obj_set_style_text_color(ui_CurrentTime, lv_color_hex(0xBDBEBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CurrentTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CurrentTime, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CurrentTime, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_CurrentTime, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CurrentTime, lv_color_hex(0x2B2F24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CurrentTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CurrentTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CurrentTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CurrentTime, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_CurrentTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CurrentTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CurrentTime, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CurrentTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CurrentTimeHeader = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_CurrentTimeHeader, 138);
    lv_obj_set_height(ui_CurrentTimeHeader, 33);
    lv_obj_set_x(ui_CurrentTimeHeader, -200);
    lv_obj_set_y(ui_CurrentTimeHeader, -200);
    lv_obj_set_align(ui_CurrentTimeHeader, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurrentTimeHeader, "Current");
    lv_obj_set_style_text_color(ui_CurrentTimeHeader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CurrentTimeHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CurrentTimeHeader, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CurrentTimeHeader, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_CurrentTimeHeader, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CurrentTimeHeader, lv_color_hex(0x7C7C7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CurrentTimeHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CurrentTimeHeader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CurrentTimeHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CurrentTimeHeader, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_CurrentTimeHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CurrentTimeHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CurrentTimeHeader, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CurrentTimeHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RetireDate = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_RetireDate, 286);
    lv_obj_set_height(ui_RetireDate, 77);
    lv_obj_set_x(ui_RetireDate, 200);
    lv_obj_set_y(ui_RetireDate, -163);
    lv_obj_set_align(ui_RetireDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RetireDate, "23:48  12/25");
    lv_obj_set_style_text_color(ui_RetireDate, lv_color_hex(0xBDBEBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RetireDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_RetireDate, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RetireDate, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_RetireDate, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RetireDate, lv_color_hex(0xC52A92), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RetireDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RetireDate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RetireDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RetireDate, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_RetireDate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_RetireDate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_RetireDate, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_RetireDate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RetireDateHeader = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_RetireDateHeader, 192);
    lv_obj_set_height(ui_RetireDateHeader, 33);
    lv_obj_set_x(ui_RetireDateHeader, 200);
    lv_obj_set_y(ui_RetireDateHeader, -200);
    lv_obj_set_align(ui_RetireDateHeader, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RetireDateHeader, "Retirement");
    lv_obj_set_style_text_color(ui_RetireDateHeader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RetireDateHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_RetireDateHeader, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RetireDateHeader, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_RetireDateHeader, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RetireDateHeader, lv_color_hex(0x7C7C7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RetireDateHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RetireDateHeader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RetireDateHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RetireDateHeader, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_RetireDateHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_RetireDateHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_RetireDateHeader, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_RetireDateHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Status1 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_Status1, 672);
    lv_obj_set_height(ui_Status1, 34);
    lv_obj_set_x(ui_Status1, -1);
    lv_obj_set_y(ui_Status1, 223);
    lv_obj_set_align(ui_Status1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Status1, "Status");
    lv_obj_set_style_text_color(ui_Status1, lv_color_hex(0x25302A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Status1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Status1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Status1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Status1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Status1, lv_color_hex(0x0A8421), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Status1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Status1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Status1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Status1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Status1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Status1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Status1, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Status1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_MainScreen, ui_event_MainScreen, LV_EVENT_ALL, NULL);

}
