// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: YouRetires

#ifndef _YOURETIRES_UI_H
#define _YOURETIRES_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
void ui_event_MainScreen(lv_event_t * e);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_MainPanel;
extern lv_obj_t * ui_DaysPanel;
extern lv_obj_t * ui_lblDaysUntil;
extern lv_obj_t * ui_Days;
extern lv_obj_t * ui_lblDays;
extern lv_obj_t * ui_YMDPanel;
extern lv_obj_t * ui_Years1;
extern lv_obj_t * ui_lblYears1;
extern lv_obj_t * ui_Months1;
extern lv_obj_t * ui_lblMonths1;
extern lv_obj_t * ui_Days1;
extern lv_obj_t * ui_lblDays1;
extern lv_obj_t * ui_CurrentTime;
extern lv_obj_t * ui_CurrentTimeHeader;
extern lv_obj_t * ui_RetireDate;
extern lv_obj_t * ui_RetireDateHeader;
extern lv_obj_t * ui_Status1;
// CUSTOM VARIABLES

// SCREEN: ui_RetirementAdjustScreen
void ui_RetirementAdjustScreen_screen_init(void);
void ui_event_RetirementAdjustScreen(lv_event_t * e);
extern lv_obj_t * ui_RetirementAdjustScreen;
extern lv_obj_t * ui_RetirementAdjustPanel;
extern lv_obj_t * ui_lblRetirementAdjust;
void ui_event_RetirementCalendar(lv_event_t * e);
extern lv_obj_t * ui_RetirementCalendar;
extern bool calendardate_trigger;
extern lv_calendar_date_t calendardate;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bluehexbg_png);    // assets/BlueHexBG.png

// FONTS
LV_FONT_DECLARE(ui_font_MontserratMedium60);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
