// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: YouRetires

#include "ui.h"

bool calendardate_trigger = false;
lv_calendar_date_t calendardate;

void GetDateFromCalendarWidget(lv_event_t * e)
{
	if(lv_calendar_get_pressed_date(ui_RetirementCalendar, &calendardate)) 
  {
    lv_calendar_set_today_date(ui_RetirementCalendar, calendardate.year, calendardate.month, calendardate.day);
    calendardate_trigger = true;
  }
}
