// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: YouRetires

#include "ui.h"

void ui_RetirementAdjustScreen_screen_init(void)
{
    ui_RetirementAdjustScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_RetirementAdjustScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RetirementAdjustScreen, lv_color_hex(0x17084F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RetirementAdjustScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RetirementAdjustPanel = lv_obj_create(ui_RetirementAdjustScreen);
    lv_obj_set_width(ui_RetirementAdjustPanel, 738);
    lv_obj_set_height(ui_RetirementAdjustPanel, 427);
    lv_obj_set_x(ui_RetirementAdjustPanel, 0);
    lv_obj_set_y(ui_RetirementAdjustPanel, 15);
    lv_obj_set_align(ui_RetirementAdjustPanel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_RetirementAdjustPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_RetirementAdjustPanel, &ui_img_bluehexbg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRetirementAdjust = lv_label_create(ui_RetirementAdjustPanel);
    lv_obj_set_x(ui_lblRetirementAdjust, 0);
    lv_obj_set_y(ui_lblRetirementAdjust, -13);
    lv_obj_set_align(ui_lblRetirementAdjust, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblRetirementAdjust, "Adjust Retirement Date");
    lv_obj_set_style_text_color(ui_lblRetirementAdjust, lv_color_hex(0xFE6B6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRetirementAdjust, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRetirementAdjust, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RetirementCalendar = lv_calendar_create(ui_RetirementAdjustPanel);
    lv_calendar_set_today_date(ui_RetirementCalendar, 2025, 1, 1);
    lv_calendar_set_showed_date(ui_RetirementCalendar, 2025, 1);
    
    lv_obj_t * ui_RetirementCalendar_header = lv_calendar_header_arrow_create(ui_RetirementCalendar);
    lv_calendar_header_dropdown_create(ui_RetirementCalendar);
    lv_obj_set_width(ui_RetirementCalendar, 685);
    lv_obj_set_height(ui_RetirementCalendar, 371);
    lv_obj_set_x(ui_RetirementCalendar, 0);
    lv_obj_set_y(ui_RetirementCalendar, 11);
    lv_obj_set_align(ui_RetirementCalendar, LV_ALIGN_BOTTOM_MID);

    lv_obj_add_event_cb(ui_RetirementCalendar, ui_event_RetirementCalendar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RetirementAdjustScreen, ui_event_RetirementAdjustScreen, LV_EVENT_ALL, NULL);

}
